version: '3.8'

services:
    db:
      image: postgres:latest
      ports:
        - '5431:5432'
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: db
